### ISSUE TITLE
permisos de ubicacion en segundo plano

### ISSUE THREAD

**Issue by jcpg1982** [guolindev/PermissionX#118]
I am using sui library to manage the permissions but I have a problem with the location permission in the background, I get the message requesting but when I accept it, I get the message again to configure it manually

**Comment by guolindev** [comment]
Background location permission is specially and complicated. It depends on the Android system version you're running and the targetSdkVersion in your project.

I may need more info to help you solve the problem. Can you share the code that you are requesting? And the screenshot of the problem that you are running into?

**Comment by jcpg1982** [comment]
![image](https://user-images.githubusercontent.com/22303139/132111231-d141bec2-62da-45d9-82f7-35051d8b1fb9.png)
![Screenshot_2021-09-04-19-32-18-784_pe com mastermachines riderAlert](https://user-images.githubusercontent.com/22303139/132111233-c5978ac3-9c3c-4085-9b13-337a09ab4222.png)
![Screenshot_2021-09-04-19-32-12-571_pe com mastermachines riderAlert](https://user-images.githubusercontent.com/22303139/132111234-16907de9-9416-4982-a4e2-b689423c7a7b.png)
![image](https://user-images.githubusercontent.com/22303139/132111251-28e24a99-4261-40d8-9eee-4bf686a72730.png)


As the images are shown I am declaring the permissions in the manifest and I request them at runtime, but the result is always the same

**Comment by guolindev** [comment]
I guess I figured out the clue. This may be strange, but that's how it worked.

Now your status is:
You are running on an Android 11 device.
Your targetSdkVersion is 30 if I am correct.
Your ACCESS_FINE_LOCATION and ACCESS_COARSE_LOCATION are allowed.
Your ACCESS_BACKGROUND_LOCATION is chosen denied and never ask again. (On Android 11, if you denied permission twice, system would consider it as you choose deny and never ask again).

So it comes to the problem that you met. 

On Android 11, background location permission can not be requested with foreground location permission together. They need to be requested separately.

So PermissionX will try to request the ACCESS_FINE_LOCATION and ACCESS_COARSE_LOCATION  first. Since they are allowed already, PermissionX will callback to onExplainRequestReason and show a dialog to indicate there's still a permission that needs to request. When you click the positive button, PermissionX will try to request ACCESS_BACKGROUND_LOCATION, but now it's selected by deny and never ask again before. So it will callback to onForwardToSettings and show the second dialog that you need to open this permission in Settings manually. 

If you jump to the settings page by click the positive button on the second dialog and open the location permission with Allow all the time option. Everything would work find.

![Screenshot_1630803816](https://user-images.githubusercontent.com/20859208/132111647-c38fd671-f7fd-42f0-805e-afbb51f75c39.png)

As I said, this permission is complicated, and have different behavior on different Android system version. If you're running on Android 10, Permission will request background and foreground location permission together, as system allow it to.

**Comment by jcpg1982** [comment]
then I must ask for the permissions separately, but I was testing in an emulator with android 10 and it is working normally, but on a physical device with android 9 I have that problem. I have already separated the permission to do it independently

**Comment by guolindev** [comment]
Oh. One thing you also should know. ACCESS_BACKGROUND_LOCATION is added on API 29, which is Android 10. On Android 9 and lower, you don't have this permission, you don't need to request it either.

Only request ACCESS_BACKGROUND_LOCATION  on Android 10 and above.

**Comment by jcpg1982** [comment]
Thank you very much I had not taken into account that these permissions are only for android 10 onwards, I am already handling them to avoid problems, again thanks for everything
