### ISSUE TITLE
not support ComponentActivity

### ISSUE THREAD

**Issue by fccaikai** [guolindev/PermissionX#158]
`PermissionX.init` only support `Fragment` And `FragmentActivity ` 

When I use the new API `registerForActivityResult` ,like https://developer.android.com/training/basics/intents/result.   

My Activity is extends `ComponentActivity`

**Comment by fanxiang123** [comment]
+1

**Comment by guolindev** [comment]
Great feedback. I will see what I can do. Thanks.

**Comment by guolindev** [comment]
Unfortunately, there's nothing I can do about this case. ActivityResult API supports ComponentActivity because Google adds the API in this layer. But it doesn't contain any Fragment-related API.
If you wrote a compose-only app, you may not need to use Fragment. But once you do, you will also need to use FragmentActivity or AppcompatActivity instead of ComponentActivity.
PermissionX injects an InvisibleFragment into your current Activity to do the permissions request flow, so if you use ComponentActivity, the whole underlying mechanism won't be able to work at all.
