### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'java.util.Set com.permissionx.guolindev.request.PermissionBuilder.grantedPermissions' on a null object reference

### ISSUE THREAD

**Issue by shtmsh** [guolindev/PermissionX#22]
java.lang.NullPointerException: Attempt to read from field 'java.util.Set com.permissionx.guolindev.request.PermissionBuilder.grantedPermissions' on a null object reference

**Comment by gs666** [comment]
是不是对象没有初始化

**Comment by guolindev** [comment]
有没有更多的堆栈信息？

**Comment by Brandon-Winterfell** [comment]
java.lang.RuntimeException:Failure delivering result ResultInfo{who=@android:requestPermissions:, request=65537, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.xxx.xxx/com.xxx.XXXActivity}: java.lang.NullPointerException: Attempt to read from field 'java.util.Set com.permissionx.guolindev.request.PermissionBuilder.grantedPermissions' on a null object reference
2 
android.app.ActivityThread.deliverResults(ActivityThread.java:4637)
3 
......
4 
Caused by:
5 
java.lang.NullPointerException:Attempt to read from field 'java.util.Set com.permissionx.guolindev.request.PermissionBuilder.grantedPermissions' on a null object reference
6 
com.permissionx.guolindev.request.InvisibleFragment.onRequestNormalPermissionsResult(InvisibleFragment.java:125)
7 
com.permissionx.guolindev.request.InvisibleFragment.onRequestPermissionsResult(InvisibleFragment.java:97)
8 
androidx.fragment.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:769)
9 
android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7787)
10 
android.app.Activity.dispatchActivityResult(Activity.java:7638)
11 
android.app.ActivityThread.deliverResults(ActivityThread.java:4633)
12 
android.app.ActivityThread.handleSendResult(ActivityThread.java:4681)
13 
android.app.ActivityThread.-wrap19(Unknown Source:0)
14 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1836)
15 
android.os.Handler.dispatchMessage(Handler.java:106)
16 
android.os.Looper.loop(Looper.java:210)
17 
android.app.ActivityThread.main(ActivityThread.java:7080)
18 
java.lang.reflect.Method.invoke(Native Method)
19 
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
20 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)

**Comment by guolindev** [comment]
上面的异常信息是使用的哪个版本的PermissionX呢？

我用最新版本的代码对了一下行号对不上。

仅从InvisibleFragment 125的空指针来判断，我认为和 https://github.com/guolindev/PermissionX/issues/10 这个issue是同一个问题，在新版中这个问题已经修复。

所以我先将这个问题关闭，如果使用最新版的PermissionX仍然还有问题的话，请再将这个issue打开。
